import * as THREE from 'three';
import {OrbitControls} from './OrbitControls.js';
const slides=[
{name:'Visão geral',title:'Uma placa.\nTodo o sistema.',cat:'01 / Anatomia do computador',desc:'Explore a base que conecta os componentes do computador. Cada setor tem um papel no funcionamento do conjunto.',label:'Explore em 3D',detail:'Gire a placa, aproxime os detalhes ou escolha um componente. Use as setas para seguir a apresentação.',loc:'12 slides · exploração livre',pos:[0,0,0]},
{name:'CPU',title:'O centro de\nprocessamento',cat:'02 / Processador e soquete',desc:'A CPU executa as instruções dos programas. O soquete estabelece a conexão elétrica e mantém o processador na posição correta.',label:'Encaixe e compatibilidade',detail:'O processador precisa ser compatível com o soquete e com o firmware da placa. O cooler foi omitido para revelar essa região.',loc:'Região superior central',pos:[-1.3,0,-2.6]},
{name:'VRM',title:'Energia na\nmedida certa',cat:'03 / Reguladores de tensão',desc:'O VRM converte e regula a energia que alimenta o processador, usando estágios de potência, indutores e capacitores.',label:'Controle térmico',detail:'Dissipadores ajudam a remover o calor dos circuitos de potência. As aletas aumentam a área de contato com o ar.',loc:'Ao redor do soquete',pos:[-3.4,0,-3.5]},
{name:'Memória',title:'Espaço para\no que está ativo',cat:'04 / Slots de memória RAM',desc:'A RAM guarda temporariamente os dados e as instruções em uso. Os módulos se conectam aos slots DIMM, próximos ao processador.',label:'Antes de instalar',detail:'A geração de memória e a sequência de instalação dependem da placa. Consulte o manual para ativar os canais corretamente.',loc:'Lado direito do processador',pos:[2.1,0,-2.6]},
{name:'Alimentação',title:'A entrada\nde energia',cat:'05 / Conectores ATX e EPS',desc:'O conector ATX de 24 pinos alimenta a placa. O conector EPS, próximo ao topo, fornece energia ao circuito do processador.',label:'Conectores diferentes',detail:'ATX, EPS e os conectores de alimentação da GPU têm funções e encaixes próprios. O modelo mostra ATX de 24 pinos e EPS de 8 pinos.',loc:'Borda direita e canto superior',pos:[4.2,0,-1.7]},
{name:'PCIe',title:'Espaço para\nexpandir',cat:'06 / Slots de expansão',desc:'Os slots PCI Express recebem placas de vídeo, rede, captura e outros dispositivos. O slot longo superior costuma ser usado para a GPU.',label:'Formato e conexão',detail:'Um slot fisicamente x16 pode ter menos pistas elétricas. A quantidade de pistas e seu compartilhamento dependem da placa e da CPU.',loc:'Metade inferior da placa',pos:[-1.5,0,2]},
{name:'M.2',title:'Armazenamento\ndireto na placa',cat:'07 / Conector M.2',desc:'O formato M.2 permite instalar um SSD compacto diretamente na placa-mãe. SSDs NVMe usam a interface PCI Express.',label:'Formato não é protocolo',detail:'Nem todo encaixe M.2 aceita os mesmos dispositivos. Comprimento, chave e suporte a SATA ou NVMe variam conforme o conector.',loc:'Entre a CPU e os slots PCIe',pos:[-.7,0,.15]},
{name:'Chipset',title:'Conexões\ncoordenadas',cat:'08 / Chipset',desc:'O chipset amplia as conexões disponíveis, atendendo parte das portas USB, SATA e outras interfaces da placa.',label:'Caminhos de comunicação',detail:'Memória e alguns slots PCIe se conectam diretamente à CPU. Outros dispositivos passam pelo chipset. Essa divisão varia entre plataformas.',loc:'Quadrante inferior direito',pos:[2.4,0,2.5]},
{name:'SATA',title:'Mais unidades\nde armazenamento',cat:'09 / Portas SATA',desc:'As portas SATA conectam SSDs de 2,5 polegadas e discos rígidos usando um cabo de dados.',label:'Dados e energia',detail:'O cabo SATA da placa transporta dados. A alimentação da unidade vem de outro cabo, ligado à fonte do computador.',loc:'Borda lateral direita',pos:[4,0,3.3]},
{name:'Painel traseiro',title:'O computador\nse conecta',cat:'10 / Entradas, saídas e áudio',desc:'O painel traseiro reúne conexões externas, como USB, rede, vídeo e áudio. Os circuitos de áudio ocupam uma região próxima à borda.',label:'Portas de vídeo',detail:'As saídas de vídeo da placa dependem do suporte da plataforma e do processador. Tipos e quantidades de portas variam entre modelos.',loc:'Borda esquerda da placa',pos:[-4.5,0,-2.5]},
{name:'UEFI e bateria',title:'Antes do sistema\noperacional',cat:'11 / Firmware e relógio',desc:'O firmware UEFI inicializa o hardware e inicia o carregamento do sistema. A bateria mantém o relógio e funções de retenção quando falta energia.',label:'Memória não volátil',detail:'O firmware fica em um chip de memória flash. A bateria não armazena o firmware e não alimenta o computador.',loc:'Região inferior central',pos:[.4,0,4.4]},
{name:'Conectores',title:'Os detalhes que\ncompletam o PC',cat:'12 / Conexões internas',desc:'Os conectores internos ligam ventoinhas, portas USB do gabinete, áudio frontal, botão de energia e indicadores luminosos.',label:'Cada pino tem uma função',detail:'A posição dos pinos e os limites elétricos dependem do modelo. Use o manual para identificar cada ligação antes da montagem.',loc:'Bordas superior e inferior',pos:[1.7,0,5.6]}
];
let current=0,exploded=false,tween=null;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const $=id=>document.getElementById(id),vp=$('viewport');
const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(37,1,.1,100);camera.position.set(12,16,15);
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch(e){$('loading').textContent='O navegador não conseguiu iniciar o 3D. Ative a aceleração gráfica e recarregue.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;vp.appendChild(renderer.domElement);$('loading').remove();
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=5;controls.maxDistance=35;controls.maxPolarAngle=Math.PI*.86;controls.autoRotateSpeed=.55;
scene.add(new THREE.HemisphereLight(0xd6efff,0x182019,2.8));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-5,14,6);scene.add(light);const rim=new THREE.DirectionalLight(0xb9f977,1.6);rim.position.set(8,4,-4);scene.add(rim);
const board=new THREE.Group();scene.add(board);const groups=Array.from({length:12},()=>new THREE.Group());groups.forEach((g,i)=>{g.userData.sector=i;board.add(g)});const picks=[];
const mat=(color,metalness=.25,roughness=.5)=>new THREE.MeshStandardMaterial({color,metalness,roughness});
const green=mat('#16403a'),black=mat('#1c252a'),silver=mat('#9ba9b0',.8,.28),gold=mat('#c6ab65',.65,.35),lime=mat('#b9f977'),dark=mat('#090f12'),blue=mat('#497d9a');
function mesh(geo,m,x,y,z,s=0){const o=new THREE.Mesh(geo,m.clone());o.position.set(x,y,z);o.userData.base=o.material.color.clone();o.userData.sector=s;groups[s].add(o);if(s)picks.push(o);return o;}
function box(x,z,w,d,h,m=black,s=0,y=0){return mesh(new THREE.BoxGeometry(w,h,d),m,x,.12+h/2+y,z,s)}
function cyl(x,z,r,h,m,s=0,y=0){return mesh(new THREE.CylinderGeometry(r,r,h,24),m,x,.12+h/2+y,z,s)}
function textLabel(text,x,z,w=1.4,s=0){const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d');ctx.fillStyle='#bbcfc8';ctx.font='500 38px monospace';ctx.textAlign='center';ctx.fillText(text,256,62);const t=new THREE.CanvasTexture(c);const p=new THREE.Mesh(new THREE.PlaneGeometry(w,w*96/512),new THREE.MeshBasicMaterial({map:t,transparent:true,side:THREE.DoubleSide}));p.rotation.x=-Math.PI/2;p.position.set(x,.137,z);groups[s].add(p);}
box(0,0,9.8,12.2,.15,green,0,-.17);
// Copper traces are schematic paths, not an electrical routing diagram.
for(let i=0;i<70;i++){const x=-4.4+(i%18)*.5,z=-5.5+Math.floor(i/18)*2.9;const pts=[new THREE.Vector3(x,.128,z),new THREE.Vector3(x+.3,.128,z+.6),new THREE.Vector3(x+.3,.128,z+1.7),new THREE.Vector3(x+.8,.128,z+2.1)];const l=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:i%3===0?0x3e7862:0x28564c,transparent:true,opacity:.75}));groups[0].add(l)}
for(const x of [-4.55,4.55])for(const z of [-5.7,0,5.7]){cyl(x,z,.15,.025,silver);cyl(x,z,.085,.03,dark,0,.025)}
textLabel('ATLAS / ATX',-1.9,5.25,2.7);textLabel('CPU',-1.25,-.95,.8);textLabel('DDR · DIMM',2.2,-5.15,1.7);textLabel('PCI EXPRESS',-2.1,4.7,2.3);textLabel('M.2',-.8,.75,.7);
// Socket and exposed CPU.
box(-1.3,-2.6,2.25,2.3,.2,dark,1);box(-1.3,-2.6,1.94,1.98,.16,silver,1,.2);box(-1.3,-2.6,1.62,1.66,.16,green,1,.36);box(-1.3,-2.6,1.46,1.5,.12,silver,1,.52);box(-.16,-2.55,.06,2.15,.08,silver,1,.25);
// VRM heatsinks with real extruded fins, chokes, capacitors.
box(-3.2,-3.1,.85,3.4,.35,black,2);for(let j=0;j<13;j++)box(-3.2,-4.62+j*.25,.86,.07,.47,silver,2,.25);
box(-1.35,-4.95,2.65,.65,.35,black,2);for(let j=0;j<12;j++)box(-2.55+j*.22,-4.95,.07,.67,.4,silver,2,.25);
for(let j=0;j<7;j++){box(-2.52,-4.1+j*.43,.32,.32,.24,silver,2);cyl(-2.07,-4.1+j*.43,.11,.24,silver,2)}
for(let j=0;j<4;j++){const x=1.23+j*.52;box(x,-2.55,.24,4.2,.38,j%2?lime:black,3);box(x,-2.55,.07,3.92,.02,dark,3,.38);for(const z of [-4.68,-.42])box(x,z,.31,.18,.53,silver,3);for(let k=0;k<38;k++)box(x,-4.4+k*.1,.035,.03,.02,gold,3,.4)}
function power(x,z,w,d,n,s){box(x,z,w,d,.53,black,s);for(let j=0;j<n;j++){const xx=x-w*.32+(j%2)*w*.64,zz=z-d*.44+Math.floor(j/2)*d/(n/2);box(xx,zz,w*.23,d/(n/2)*.65,.015,dark,s,.53)}}
power(4.13,-2,.57,2.65,24,4);power(-3.1,-5.6,1,.5,8,4);
for(const z of [1.3,3.15]){box(-1.55,z,5.4,.32,.36,black,5);box(-1.55,z,5.1,.1,.02,gold,5,.36);box(1.15,z,.32,.5,.48,silver,5);for(let k=0;k<45;k++)box(-4.02+k*.11,z,.05,.1,.025,dark,5,.38)}box(-3.25,4.25,1.9,.3,.3,black,5);
box(-.7,.12,3.1,.72,.1,green,6);for(let j=0;j<3;j++)box(-1.55+j*.72,.12,.5,.5,.12,dark,6,.1);box(-2.31,.12,.2,.74,.25,black,6);cyl(.85,.12,.085,.06,silver,6,.11);
box(2.45,2.35,1.9,1.8,.23,dark,7);box(2.45,2.35,2.1,2,.27,silver,7,.23);for(let i=0;i<9;i++)box(1.56+i*.22,2.35,.075,1.95,.12,black,7,.5);
for(let i=0;i<4;i++){box(4.1,2.35+i*.65,.7,.48,.55,black,8);box(4.46,2.35+i*.65,.02,.3,.29,gold,8,.1)}
for(let i=0;i<5;i++){let z=-4.55+i*.85;box(-4.36,z,.95,.72,.9,silver,9);box(-4.85,z,.025,.5,.58,dark,9,.12);box(-4.87,z,.03,.4,.11,i<3?blue:gold,9,.27)}
box(-4.1,3.5,.65,.65,.14,dark,9);for(let i=0;i<5;i++)cyl(-4.25,1.2+i*.5,.13,.4,gold,9);textLabel('AUDIO',-4.1,4.9,1);
cyl(.1,4.25,.51,.16,black,10);cyl(.1,4.25,.44,.18,silver,10,.07);box(1.2,4.35,.52,.65,.14,dark,10);for(let i=0;i<4;i++)for(const x of [.85,1.55])box(x,4.1+i*.15,.16,.065,.07,silver,10);
for(const [x,z,w,n]of [[2.4,5.5,1.3,10],[-1.8,5.55,1.1,8],[-3.35,5.55,.8,8],[3.7,.1,.55,4],[.15,-5.6,.55,4]]){box(x,z,w,.33,.2,black,11);for(let j=0;j<n;j++)box(x-w*.4+(j%(n/2))*w*.8/(n/2-1),z+(j<n/2?-.09:.09),.045,.045,.28,gold,11,.2)}
for(let i=0;i<28;i++){const x=-3.7+(i%7)*.88,z=.8+Math.floor(i/7)*1.2;if((x>.8&&z>1.5)||z===.8)continue;box(x,z,.14,.25,.07,black);}
const tagButtons=slides.slice(1).map((s,i)=>{const b=document.createElement('button');b.className='tag';b.textContent=s.name;b.addEventListener('click',()=>select(i+1));$('labels').append(b);return b});
slides.forEach((s,i)=>{const b=document.createElement('button');b.innerHTML=`<b>${String(i+1).padStart(2,'0')}</b>${s.name}`;b.addEventListener('click',()=>select(i));$('rail').append(b)});
function focus(pos,overview=false,top=false){const t=new THREE.Vector3(...pos);const dst=overview?new THREE.Vector3(12,16,15):t.clone().add(new THREE.Vector3(7.5,11,10));if(top)dst.copy(t).add(new THREE.Vector3(0,overview?19:13,.01));tween={from:camera.position.clone(),to:dst,start:performance.now(),targetFrom:controls.target.clone(),targetTo:t};if(reduced){camera.position.copy(dst);controls.target.copy(t);tween=null;}}
function select(i){current=Math.max(0,Math.min(11,i));const s=slides[current];$('category').textContent=s.cat;$('title').innerText=s.title;$('description').textContent=s.desc;$('detailLabel').textContent=s.label;$('detail').textContent=s.detail;$('location').textContent=s.loc;$('counter').textContent=`${String(current+1).padStart(2,'0')} / 12`;$('selection').textContent=s.name;$('prev').disabled=current===0;$('next').disabled=current===11;[...$('rail').children].forEach((b,j)=>{b.classList.toggle('active',j===current);b.setAttribute('aria-current',j===current?'step':'false')});picks.forEach(o=>{o.material.emissive.setHex(o.userData.sector===current?0x385914:0x000000);o.material.emissiveIntensity=.45});tagButtons.forEach((b,j)=>b.classList.toggle('active',j+1===current));focus(s.pos,current===0);}
$('prev').onclick=()=>select(current-1);$('next').onclick=()=>select(current+1);$('home').onclick=()=>focus([0,0,0],true);$('top').onclick=()=>focus(slides[current].pos,current===0,true);$('explode').onclick=()=>{exploded=!exploded;$('explode').setAttribute('aria-pressed',exploded);$('explode').textContent=exploded?'Reunir peças':'Separar peças'};$('rotate').onclick=()=>{controls.autoRotate=!controls.autoRotate;$('rotate').setAttribute('aria-pressed',controls.autoRotate);$('rotate').textContent=controls.autoRotate?'Pausar giro':'Girar'};
function zoom(f){tween=null;const offset=camera.position.clone().sub(controls.target);offset.setLength(THREE.MathUtils.clamp(offset.length()*f,controls.minDistance,controls.maxDistance));camera.position.copy(controls.target).add(offset)}$('plus').onclick=()=>zoom(.8);$('minus').onclick=()=>zoom(1.25);$('full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{$('full').textContent='Use F11 para ampliar'}};document.addEventListener('fullscreenchange',()=>{$('full').textContent=document.fullscreenElement?'Sair da tela cheia':'Tela cheia ⛶'});
document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();select(current+1)}if(e.key==='ArrowLeft'){e.preventDefault();select(current-1)}if(e.key==='Home'){e.preventDefault();select(0)}});
controls.addEventListener('start',()=>tween=null);let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const r=renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(picks)[0];if(hit)select(hit.object.userData.sector)});
new ResizeObserver(()=>{const w=vp.clientWidth,h=vp.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}).observe(vp);
function frame(t){requestAnimationFrame(frame);if(tween){const p=Math.min((t-tween.start)/850,1),k=1-Math.pow(1-p,3);camera.position.lerpVectors(tween.from,tween.to,k);controls.target.lerpVectors(tween.targetFrom,tween.targetTo,k);if(p===1)tween=null}groups.forEach((g,i)=>{const y=exploded&&i? .65+(i%3)*.42:0;g.position.y=reduced?y:THREE.MathUtils.lerp(g.position.y,y,.07)});controls.update();tagButtons.forEach((b,i)=>{const s=slides[i+1];const p=new THREE.Vector3(s.pos[0],groups[i+1].position.y+.95,s.pos[2]).project(camera);const show=(current===0?[1,3,5,7].includes(i+1):current===i+1)&&p.z<1&&Math.abs(p.x)<.9&&Math.abs(p.y)<.75;b.style.display=show?'block':'none';b.style.left=(p.x*.5+.5)*vp.clientWidth+'px';b.style.top=(-p.y*.5+.5)*vp.clientHeight+'px'});renderer.render(scene,camera)}select(0);requestAnimationFrame(frame);
